version: "3"
services:
  app:
    command: "tail -f /dev/null"
    image: "openjdk:11"
    ports:
      - "8080:8080"
    volumes:
      - "./:/app"
    working_dir: "/app"
  db:
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    expose:
      - "3306"
    image: "mariadb:10"
    volumes:
      - "./docker-compose/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro"
  phpmyadmin:
    environment:
      PMA_HOST: "db"
      PMA_PASSWORD: "my-secret-pw"
      PMA_USER: "tsuzuru"
      PMA_USER_CONFIG_BASE64: "PD9waHAKJGNmZ1snQWxsb3dUaGlyZFBhcnR5RnJhbWluZyddID0gdHJ1ZTsK"
    expose:
      - "80"
    image: "phpmyadmin/phpmyadmin:5"
