version: "3"
services:
  app:
    command: "tail -f /dev/null"
    image: "openjdk:11"
    ports:
      - "8080:8080"
    volumes:
      - "./:/app"
    working_dir: "/app"
  db:
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    expose:
      - "3306"
    image: "mariadb:10"
    volumes:
      - "./docker-compose/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro"
